.travis.yml, package.json, tsconfig.json
Update to emit es6 and remove `es6-promise` typings.
=> emit es6 and drop es6-promise typings

package.json, src/main.ts, src/webpack.config.js, tests/support/MockModule.ts, tests/unit/main.ts
Resolves https://github.com/dojo/cli-build/issues/6
Mostly just webpack config additions. Will automatically load `main.styl` in the the `src` folder, any generated css will currently be included in the js bundle. Further enhancements would be to use the ExtractTextPlugin to put this back as an external css file.
=> Add stylus support

package.json, src/webpack.config.js
Adds support of sourcemaps back to original TS (rather than just the unminified JS) for our dojo 2 dependencies. Unfortunately the official webpack source-map-loader looks dead as a project, with an outstanding PR that fixes up the sourcemap source paths, so I've had to use a fork.
=> Support sourcemaps for dojo 2 dependencies

package.json, src/webpack.config.js
Fixes https://github.com/dojo/cli-build/issues/9
Styles are now extracted to a separate `main.css` file, and source maps are generated. The html link tag for the stylesheet will be automatically injected by the HTML plugin.
=> Extract CSS to separate file rather than loading from bundle

src/webpack.config.js
**Type:** bug
Makes the filenames for resources generated by webpack more readable (previously were just hashes). Also now retains the original folder structure of the files also.
=> Make webpack resource paths more readable

src/webpack.config.js
This PR adds CSS module support to the build command. It makes use of [webpack/css-loader](https://github.com/webpack/css-loader) for CSS compilation and inlining rather than relying on a custom plugin or loader. It's probably easiest to walk through an example development flow for an end user:
1. Generate a Dojo 2 app.
```
dojo create app --name testApp
```
2. Create a CSS module at `testApp/src/styles/example.css` (file name and location don't matter).
```css
.someClass {
background: red;
}
```
3. Generate typings to leverage TS intellisense (using dojo/cli-css-typings#3). A type declaration file will be generated at `testApp/src/styles/module.css.d.ts`.
```
dojo css typings --out testApp/src/styles/ …
```
=> Enable CSS module support

package.json, src/webpack.config.js
This replaces my very hacky webpack plugin, with my slightly less hacky webpack loader. The loader sniffs for the TypeScript UMD style, it then uses recast to modify the AST which means the source map is correct after modifications.
This should now mean we can leverage lazy requires (like `require.context`, and `require(someVar)`), which before we couldn't do with the umd-compat-plugin, as you had to ignore them and require became a no-op.
As a side effect, I've now had to add an ignore context for `dojo/app`, as webpack now picks up the dynamic require.
=> Use umd-compat-loader

src/webpack.config.js
**Type:** bug
Fixes the regex used when configuring the `ContextReplacementPlugin`
Resolves #23
=> Make regex safe for Windows

package.json, src/main.ts, src/webpack.config.js, tests/unit/main.ts
This PR adds bundle size reporting to production webpack builds by generating a `report.html` file in the `dist` folder. It makes use of [bitpshr/webpack-bundle-analyzer-sunburst](https://github.com/bitpshr/webpack-bundle-analyzer) which was forked from [th0r/webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer) and modified to support non-commercial sunbursts charts via a [hand-rolled d3 implementation](https://github.com/bitpshr/webpack-bundle-analyzer/blob/master/client/components/Sunburst.jsx). I manually tested this on a generated Dojo 2 app, TodoMVC, and Monster Cards, and everything seemed fine. I verified that the size of each file on disk equaled the parsed file size in the report. …
=> Bundle size reporting

src/webpack.config.js
=> Removed tsx and rxjs refs from webpack config

src/webpack.config.js
Revised css-module process will now output a UMD format `.js` file rather than a `json` file.
`json-css-module-loader` still needs a release / tests before this code will work correctly.
Resolves https://github.com/dojo/widgets/issues/272
=> CSS module loading in umd format

src/webpack.config.ts
Uses the module replacement plugin to replace css requests with css.js requests when such a file exists. This allows widgets to import css using the `.css` extension.
Resolves https://github.com/dojo/widgets/issues/16
=> Use module replacement to allow widgets to import with `.css` extension

Gruntfile.js, package.json, src/main.ts, src/templates/custom-element.html, src/templates/custom-element.ts, src/webpack.config.ts, tests/intern.ts
Adding additional options to generate custom element packages and imports. 
Usage:
```bash
$ dojo build --element=src/widget/createMyWidgetElementDescriptor
```
This will bundle all of the dependencies from `createMyWidgetElementDescriptor` (usually your widget) and create the files,
* `dist/my-widget/my-widget.js` - JS for your widget
* `dist/my-widget/widget-core.js` - JS for widget core
* `dist/my-widget/my-widget.css` - CSS for your widget
* `dist/my-widget/my-widget.html` - HTML import containing all your widget dependencies
There is an optional parameter to name the output files, `--elementPrefix`, that you can specify if your input file does not follow the convention `createXYZElement`.
To use in an HTML …
=> Adding options to build components

package.json, src/main.ts, tests/unit/main.ts
**Type:** bug
**Description:** 
Fix help display so that it displays options per grouping
*Note:* taken and updated https://github.com/dojo/cli-build/pull/26
**Related Issue:** #58
Please review this checklist before submitting your PR:
=> Fix help so it displays per grouping

src/webpack.config.ts
Adding an extra configuration variable to support lazy widget loading.
Resolves https://github.com/dojo/examples/issues/183
=> Configuration to work with lazy widgets, examples-183

src/webpack.config.ts
**Type:** bug
Currently it's not possible to `grunt link` this project due to some behaviour we depend on in dts-loader. Turns out this did actually work fine pre webpack 2 conversion https://github.com/dojo/cli-build/pull/67, because we actually had the local node_modules in our resolving paths (https://github.com/dojo/cli-build/blob/b727d5256816db14d6c39421da6912d2c3fc7ea6/src/webpack.config.ts#L173)
=> Add local node_nodules resolution to fix grunt link

src/main.ts, src/webpack.config.ts, src/webpack.d.ts, tests/unit/main.ts
Fixes custom element generation from cli-build.
Also,
* Cleaned up some dead code around `dojo-core/request`
* Added `--profile` option for creating the `.json` file you can upload to webpack's analyzer
* Ignoring `@dojo/core/request/providers/node` because that probably shouldn't be bundled for the browser (plus its hugemongus)
* Added some missing tests around custom element configuration
Note: The `InjectModulesPlugin` appears to be unused now, so we might be able to just delete it.
=> Fixing widget-core split, adding profile option

package.json, src/main.ts, tests/unit/main.ts
Add's eject hint output:
Requires CLI release
Resolves #81
=> Adds hint to eject command

src/plugins/I18nPlugin.ts, src/webpack.config.ts
**Type:** bug
Fixes a couple bugs uncovered while running `$ dojo test` that went uncaught with just `$ dojo build`.
- Output a resolvable mid for `@dojo/core/request/providers/node` in the `externals` webpack configuration option.
- Fix issue in the I18nPlugin in which the ast map is prematurely cleared in certain cases.
=> Webpack config and I18nPlugin fixes.

package.json, src/main.ts, src/webpack.config.ts
Manual lazy loading bundling using `.dojorc`.  `.dojorc` looks like this:
```json
{
"build-webpack": {
"bundles": {
"widgets": [
"src/widgets/TodoFooter",
"src/widgets/ViewChooser",
"src/widgets/TodoFilter"
]
}
}
}
```
This will create a `widgets.js` file containing `TodoFooter`, `ViewChooser`, and `TodoFilter`.
Resolves #90
=> Adding manual bundling from .dojorc, issue #90

package.json, src/webpack.config.ts
Add tslinting for projects that have a `tslint.json` file in the root of the project.
Resolves #96
=> Support opt-in loader for tslint

src/loaders/css-module-decorator-loader/loader.ts, src/webpack.config.ts, tests/unit/loaders/css-module-decorator-loader.ts
Modifies the build command to process `.m.css` and leave `.css` files alone.
Resolves https://github.com/dojo/widgets/issues/76
=> Processing `.m.css` instead of `.css`

src/webpack.config.ts
**Type:** bug
The node provider should be ignore from the webpack build.
Resolves #115
=> Ignore request node provider

src/webpack.config.ts
Turn off uglifying when in watch or test modes, should dramatically decrease build times.
=> Don't uglify on watch or test

src/webpack.config.ts
We should probably fix `includeWhen` as a follow up to be less surprising in behaviour.
=> Fix return type to be an array when using includeWhen

Gruntfile.js, src/banner.md, src/webpack.config.ts, src/webpack.d.ts
**Type:** bug
Add `src/banner.md` that contains any text (e.g., the Dojo license) that needs to be prepended as a comment to the output build source.
Resolves #108
=> Add Dojo license to the top of all builds.

src/plugins/CoreLoadPlugin.ts, src/webpack.config.ts, tests/unit/plugins/CoreLoadPlugin.ts
**Type:** bug
Introduce a flag (set within the webpack config to true when `args.withTests` is true) to `CoreLoadPlugin` that allows all app modules to be added to the internal mid map, so that they can be lazy-loaded without parsing, as long as the modules have already been loaded by webpack.
Resolves #106
=> CoreLoadPlugin: add option to map all app mids.

src/webpack.config.ts
Add support to build `jsx` files.
Resolves #128
=> support jsx files

README.md
**Type:** bug
Ensure that the package is referred to correctly as `cli-build-webpack` in the readme and use the fully qualified command i.e. `dojo build webpack` over `dojo build`.
Resolves #130
=> Consistently name the package and command throughout the readme

src/webpack.config.ts
**Type:** bug
Remove additional (and incorrect) normalization of `args.supportedLocales` and `args.messageBundles` before passing them to `I18nPlugin`. Verified against `dojo/examples/todo-mvc-kitchensink`.
Resolves #140
=> Fix: do not reformat i18n args.

src/plugins/I18nPlugin.ts, src/webpack.config.ts, tests/unit/plugins/I18nPlugin.ts
**Type:** bug
When running in `watch` mode, cache any CLDR data URLs parsed from previous builds in order to prevent future, partial builds from obliterating injected CLDR data.
The one downside to caching URLs is that any removed URLs will not be removed from the build until after a hard restart. But given that CLDR data will be rarely added or removed from a project, this is unlikely to be problematic.
Resolves #125
=> Add option to reuse CLDR data from previous builds

src/webpack.config.ts
**Type:** bug
Webpack can now load our font files
Resolves #147
=> Add webpack font file extensions to file-loader rule

src/webpack.config.ts
Using the long css module ident provides human readable class names to tests and more importantly to the `expectRender` diff output.
Resolves #155
=> Use long css-module ident when compiling with tests

src/webpack.config.ts
**Type:** bug
Update the path separator used in the regular expression that triggers the `imports-loader` on Globalize.js modules.
Fix verified on Windows 10.
Resolves #162
=> Hotfix: use the correct path separator for imports-loader.

README.md
**Type:** Formatting
Fixes formatting of the `externals` documentation in the README.
=> Fix formatting of externals config section of README

src/loaders/css-module-dts-loader/loader.ts, tests/unit/loaders/css-module-dts-loader.ts
**Type:** bug
- fix unescaped regex
- modified the 'should not generate dts files if no css imports are found' test to catch the issue and to show that the fix works
Resolves #193
=> fix unescaped '.' in dts-loader regex

src/webpack.config.ts, src/webpack.d.ts
**Type:** bug
- add Node interface to webpack.d.ts
- add 'empty' node config for dgram, fs, net, and tls modules
Resolves #187
=> Add node webpack setting

src/plugins/IgnoreUnmodifiedPlugin.ts, src/webpack.config.ts, src/webpack.d.ts, tests/support/webpack/Compiler.ts, tests/unit/all.ts, tests/unit/plugins/IgnoreUnmodifiedPlugin.ts
**Type:** bug
The `css-module-dts-loader` creates new `d.ts` files for each CSS file, but each new `d.ts` triggers a compilation. This PR utilizes the `WatchIgnorePlugin` to prevent files ending in `.css.d.ts` from triggering builds. There may be a better way to solve this problem, but setting `watchOptions.ignored` or `exclude` on the relevant loaders has no effect. This fix has been verified using the reproduction steps listed in the issue.
Resolves #137
=> Prevent css.d.ts files from triggering builds.

package.json, src/main.ts, tsconfig.json, typings.json
Migrate to use `@dojo/interfaces/cli` and `@types` for other typings.
Depends on a release of `@dojo/interfaces`.
Refs: https://github.com/dojo/cli/issues/119
=> Migrate to @dojo/interfaces/cli and @types

src/webpack.config.ts, tests/support/MockModule.ts, tests/unit/webpack.config.ts
**Type:** bug
Uses the `name` from package.json to generate a valid JavaScript function name to be used as the `output.jsonpFunction`, effectively preventing different builds from accidentally loading from the wrong bundle. The config uses simple character replacement to separate words with an underscore. For example `@dojo/cli-build-webpack` would become `dojoWebpackJsonp_cli_build_webpack`.
These changes were verified locally against an application containing multiple independent bundles.
Resolves #158
=> Use the package name to set the jsonpFunction

src/webpack.config.ts, tests/unit/webpack.config.ts
**Type:** bug
Update the `output` configuration for custom element builds so that they are build with a jsonp wrapper, as opposed to a UMD wrapper, and also remove additional library-specific `output` configuration options. Changes have been verified locally with a test application that builds two separate custom elements.
Resolves #202
=> Change output format for custom elements

package.json, src/webpack.config.ts
**Type:** bug
Removes the `resolve-url-loader` from the Webpack configuration.
Resolves #204
=> Remove resolve-url-loader

README.md, src/main.ts, tests/unit/main.ts
Adding an error message if you try to start the dev server and the port is in use. Note that this is not specifically checking if the watch command is already running, just that the specified port is available.
Resolves #86
=> Adding check for port in use, issue #86

src/main.ts, src/webpack.d.ts, tests/unit/main.ts
**Type:** bug
Errors during the webpack build will now return a rejected promise. With this, `dojo test` will fail when you have build errors.
Resolves https://github.com/dojo/cli-test-intern/issues/31
=> Compliation errors cause the build to fail now, dojo/cli-test-itern#31

src/webpack.config.ts, tests/unit/webpack.config.ts
This PR will make the webpack build fail (right away) if there are tslint problems when doing a regular (`dojo build`) build. If you use watch (`-w`) or tests (`-t`) the lint errors will only generate warnings.
Resolves #207
=> Failing on lint errors when doing a regular build

.gitignore, package.json, src/webpack.config.ts, tests/intern.ts, tests/unit/webpack.config.ts
This adds support for using `import()` over `@dojo/core/load` in projects. It supports automatic lazy widget bundling, as well as bundles defined in the `.dojorc` like the existing functionality via `@dojo/core/load`.
This will mean users can now do:
```
registry.define('my-widget', async function () {
const Module = await import('./MyWidget');
return Module.default;
});
```
over:
```
registry.define('my-widget', async function () {
const Module = await load(require, '/MyWidget');
return Module.default;
});
```
Although this doesn't change much to an end user, we are at least using a standard, and it will eventually mean we can remove a fair amount of code from `cli-build` …
=> Add imports() support

src/plugins/CoreLoadPlugin.ts, src/plugins/I18nPlugin.ts, src/plugins/util/main.ts, src/webpack.config.ts, tests/unit/plugins/CoreLoadPlugin.ts, tests/unit/plugins/I18nPlugin.ts, tests/unit/plugins/InjectModulesPlugin.ts, tests/unit/plugins/util/i18n.ts, tests/unit/plugins/util/main.ts, tests/unit/webpack.config.ts
**Type:** bug
Changes have been verified with `todo-mvc-kitchensink` on both Windows and Mac. Updates operations that read and manipulate file paths to correctly account for the OS's file separator. Fixes a number of bugs on Windows:
* `umd-compat-loader` now uses the bundle's name.
* `CoreLoadPlugin` maps module IDs correctly.
* `InjectModulesPlugin` is able to load the specified modules.
* Supported locale bundles are properly included in the build.
Resolves #218
=> Fix assumptions about path separator

package.json
**Type:** bug
This updates the version of bundle analyzer plugin used by the build process. There aren't really tests in place to validate the output of the build, but I did test it against todo-mvc with and without some additional `bundle` options in `.dojorc`. The convention used is that if there is only one bundle it is still created as `dist/report.html`, and if there are multiple bundles each will get a `dist/report-{bundleName}.html` file.
Resolves #99
=> Update bundle analyzer plugin version

.appveyor.yml, .travis.yml, intern.json
`grunt-dojo2` has been updated in [a PR](https://github.com/dojo/grunt-dojo2/pull/162) to use Intern 4 exclusively which includes a reporter similar to the one developed for Intern 3. This PR updates the CI scripts to use these features and return the grunt tasks back to feature parity with the tasks before the Intern 4 conversion. The `grunt-dojo2` PR **MUST LAND** and be released before this can land.
=> Update CI for new release of grunt-dojo2

src/main.ts
This removes the explicit 127.0.0.1 address from the `listen()` method of the
WebpackDevServer launched by the `build --watch` command, as that hinders the
possibility of running it inside a Docker container.
Resolves #248
=> Do not listen only on the loopback interface (#248)

src/plugins/util/i18n.ts, tests/support/mocks/ast/README.md, tests/support/mocks/ast/cldr-sequence.json, tests/unit/plugins/util/i18n.ts
**Type:** bug
`@dojo/i18n/cldr/load.default` can be required from within a sequence expression, which appears to be the case when building an application with the `--withTests` flag. This PR adds a check for such calls, and has been verified against the [`todo-mvc-kitchensink`](https://github.com/dojo/examples) tests.
Resolves #246
=> Fix: parse `@dojo/i18n/cldr/load` requires from sequence expressions.

src/webpack.config.ts
**Type:** bug
Previously, the static optimizer plugin has access to all JS files by virtue of the fact that it was accessing the compilation. When I moved it to a loader, I only added it to the `src/**.ts` files. This updates it to properly optimize any JS files in the build.
Resolves #244
=> Optimize all js files

package-lock.json, package.json, src/webpack.config.ts, src/webpack.d.ts, tests/unit/webpack.config.ts
**Type:** bug
Adds the `clean-webpack-plugin` to remove the `dist` and `_build` directories at the start of compilation. Verified against [`todo-mvc-kitchensink`](https://github.com/dojo/examples).
Resolves #228
=> Add clean-webpack-plugin

Gruntfile.js, src/main.ts, src/templates/custom-element.js, src/templates/custom-element.ts, src/webpack.config.ts, src/webpack.d.ts, tests/unit/main.ts
Adds support for building a custom element that is defined with the new decorator, and fixes a couple minor issues with the existing custom element build:
* If building a custom element in a dependency, the `--element` flag will not end in `.ts`. Previously this meant that the prefix name could not be automatically determined; this updates it so that it works in either case.
* `templates/custom-element.ts` is compiled with a target of es6 (as are all the ts files), but it gets fed through uglifyJS and runs in the browser. Using `let` breaks this file, and it probably shouldn't be run through that pipeline if doing something perfectly valid in the source file creates invalid output. Now it's a JS file
=> Update custom elements build

src/webpack.config.ts
**Type:** bug
Correct the config options for the `tslint-loader`.
Resolves #258
=> Correct the options for tslint-loader

package-lock.json, src/templates/custom-element.js, src/webpack.config.ts
This PR updates the template files used during custom element injection to support either a custom element descriptor (as was previously expected) or a decorated class. This change arose from [dojo/widgets#837](https://github.com/dojo/widget-core/issues/837).
=> Support custom element descriptors as well as decorated classes
