src/main.ts
tests/unit/main.ts

Fix the path resolution of webpack-dev-server client

---

src/webpack.config.js

Fix build on Windows

---

package.json

Upgrade ts-loader to version 1.0.0

---

package.json
typings.json

**Type:** bug
Fixes the intern version and typings.

Fix Intern version and typings

---

package.json

**Type:** bug 
Fixes an EMFILE issue.
Resolves https://github.com/dojo/cli-build/issues/35

Update copy webpack plugin

---

package.json
src/main.ts
src/webpack.config.js
tests/support/MockModule.ts
tests/unit/main.ts

Adds a flag to build test files, and fixes issues with unit tests caused by modules being cached between tests. Related to: https://github.com/dojo/cli/issues/13

Build test files

---

src/plugins/CoreLoadPlugin.ts
src/plugins/I18nPlugin.ts
src/webpack.config.js
tests/intern.ts
tests/unit/plugins/CoreLoadPlugin.ts
tests/unit/plugins/I18nPlugin.ts

**Type:** bug
Update references to scoped packages. Supersedes #44.

Update @dojo/core references in CoreLoadPlugin.

---

README.md

[skip ci]
**Type:** bug
Refs dojo/meta#135

Updated readme with correct npm version badge

---

src/webpack.config.ts

**Type:** bug
Updates the source maps config for @dojo namespaced packages.
Resolves #55

update source maps config for @dojo namespace

---

package.json
src/webpack.config.ts

**Type:** bug
Adds `file-loader`.
Resolves #63

Add file loader for image files

---

package.json

**Type:** bug
Update commit hash for source map dependency.

Update the commit for source map loader

---

package.json

**Type:** bug
Update `@dojo/core` to alpha.26 and `@dojo/i18n` to alpha.8.

Update @dojo/core and @dojo/i18n

---

package.json

Adding min deps for node 6 and npm 3

---

package.json
src/webpack.config.ts

* Forked https://github.com/bryanforbes/source-map-loader as https://github.com/rorticus/source-map-loader
* Published to npm as `source-map-loader-cli`
* Updated deps to point to `source-map-loader-cli`
Resolves #76

Updating to use NPM dep of bryans source-map-loader fork

---

package.json
src/loaders/css-module-dts-loader/loader.ts

Upgrade typescript to `2.3.2`
Resolves #132

update typescript to 2.3.2

---

src/loaders/css-module-dts-loader/loader.ts

**Type:** bug
Fix incorrect changes from ts2.3.2 upgrade.

Fix incorrect changes from ts2.3.2 upgrade

---

package.json
src/webpack.config.ts

Adds `OptimizeCssAssetsPlugin` for dist mode.
Resolves #123

Include optimize-css-assets-webpack-plugin for dist build.

---

package.json
src/main.ts
tests/unit/main.ts

Related to the proposed [process change](https://github.com/dojo/meta/issues/183) for managing pre-release `beta` and `rc` release sets
Related to https://github.com/dojo/meta/issues/183

Move to next tag for @dojo deps

---

src/loaders/css-module-dts-loader/loader.ts
src/main.ts
src/plugins/InjectModulesPlugin.ts
tests/unit/plugins/InjectModulesPlugin.ts

**Type:** bug
This just updates usage of @dojo/shim so that this can compile against the latest version.

Fix promise compilation errors

---

tsconfig.json

Upgrading to use new shim library here, https://github.com/dojo/shim/pull/101. Only thing needed was inclusion of promise typings.

Upgrading to new dojo/shim

---

src/plugins/CoreLoadPlugin.ts
tests/unit/loaders/css-module-dts-loader.ts
tests/unit/plugins/CoreLoadPlugin.ts
tests/unit/plugins/I18nPlugin.ts
tests/unit/plugins/util/i18n.ts
tests/unit/webpack.config.ts

@maier49 's PR here, https://github.com/dojo/cli-build-webpack/pull/176 but rebased onto master.
Resolves #174

Fix using command on Windows

---

.appveyor.yml
README.md

Adding Appveyor support! Note that there will be failures in Windows until those tests are fixed.

Adding appveyor support

---

package.json

Removing `imports-loader` from `dependencies`, and leaving the one in `devDependencies`.
Resolves #190

Removing duplicate dependency

---

tests/unit/plugins/InjectModulesPlugin.ts

**Type:** bug
Update the InjectModulesPlugin unit tests to correctly fail on error.
Resolves #143

Fix InjectModulesPlugin tests

---

.appveyor.yml
.travis.yml
Gruntfile.js
package.json
src/getFeatures.ts
src/plugins/CoreLoadPlugin.ts
src/plugins/I18nPlugin.ts
tests/intern.ts
tests/support/MockModule.ts
tests/unit/getFeatures.ts
tests/unit/loaders/css-module-decorator-loader.ts
tests/unit/loaders/css-module-dts-loader.ts
tests/unit/main.ts
tests/unit/plugins/CoreLoadPlugin.ts
tests/unit/plugins/ExternalLoaderPlugin.ts
tests/unit/plugins/I18nPlugin.ts
tests/unit/plugins/IgnoreUnmodifiedPlugin.ts
tests/unit/plugins/InjectModulesPlugin.ts
tests/unit/plugins/util/i18n.ts
tests/unit/plugins/util/main.ts
tests/unit/postcss.config.ts
tests/unit/webpack.config.ts
tsconfig.json

Updating to intern 4! Depends on https://github.com/dojo/grunt-dojo2/pull/146
Resolves #180

Upgrading to intern 4

---

package.json
src/webpack.config.ts
tests/unit/webpack.config.ts

**Type:** bug
Uses CssModulePlugin and next version of webpack-contrib css-module-dts-loader to fix this bug.
Resolves #112

External css with webpack contrib

---

.gitignore

Refs: dojo/meta#205
Updates `.gitignore` for Intern 4 for dojo/meta#205

Update .gitignore for Intern 4

---

package.json

Upgrade to Intern 4.1

---

package.json
src/webpack.config.ts
tsconfig.json

Updating to use tslib from https://github.com/dojo/shim/pull/114/files and the intern loader from grunt dojo2

Using loader from grunt-dojo2 and tslib from shim

---

package.json

Upgrade dojo dependencies

---

package-lock.json
package.json
src/plugins/CoreLoadPlugin.ts
src/plugins/I18nPlugin.ts
src/plugins/InjectModulesPlugin.ts
src/plugins/util/i18n.ts
src/webpack.config.ts
tests/support/webpack/Pluginable.ts
tsconfig.json

Upgrade to TypeScript 2.6 and turn on strict

---

README.md

Change status to deprecated
